#theme: jekyll-theme-architect
title: "Differential Machine Learning (2020)"
email: differential.ml@deep-analytics.org
description: "Notebooks implementing the novel ideas in the working paper: Differential Machine Learning, by Brian Huge and Antoine Savine"
twitter_username: SavineAntoine
github_username: differential-machine-learning
